project_id = "xiwcdhmjekwcousinmce"

[functions.ml-oauth]
verify_jwt = false

[functions.ml-api]
verify_jwt = false

[functions.ai-optimize]
verify_jwt = false

[functions.extract-product]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = false

[functions.retry-webhooks]
verify_jwt = false
